expr: Experiment

device: cuda

data:
  dataset: MNIST
  mode: train # should consider train or test!

model:
  name: VAE
  latent_size: 100
  x_size: [1, 28, 28]

loss_fn: ELBO
 
hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 100
  batch_size: 16

save_path: saved

load_weights: vae.mnist.200epochs.pth