expr: Experiment

task: gen # 'recon' or 'gen'

device: cuda

data:
  dataset: CelebA
  mode: test # should consider train or test!

model:
  name: VAE
  dims: [3, 32, 64, 128, 256]
  latent: 128
  img_size: [3, 128, 128]

save_path: saved

load_weights: vae.celeba.200epochs.pth