expr: Experiment

task: gen # 'recon' or 'gen'

device: cuda

data:
  dataset: MNIST
  mode: test # should consider train or test!

model:
  name: VAE
  dims: [1, 32, 64]
  latent: 16
  img_size: [1, 28, 28]

save_path: saved

load_weights: vae.mnist.100epochs.pth