expr: Experiment

device: cuda

model:
  name: VAE
  dims: [3072, 1000, 700]
  latent: 500

hyperparams:
  batch_size: 128

save_path: saved

image_size: [3, 32, 32]

load_weights: vae.cifar10.010epochs.pth