expr: Experiment

device: cuda:2

model:
  name: VAE
  dims: [3, 32, 64, 128]
  latent: 100
  img_size: [3, 128, 128]

hyperparams:
  batch_size: 128

save_path: saved

load_weights: vae.celeba.020epochs.pth