expr: Experiment

device: cuda

data:
  dataset: CIFAR10
  mode: train # should consider train or test!

model:
  name: VAE
  dims: [3072, 1000, 700]
  latent: 500

loss_fn: 
  name: ELBO
 
hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 200
  batch_size: 128

save_path: saved