expr: Experiment

device: cuda:2

data:
  dataset: CelebA
  mode: train # should consider train or test!

model:
  name: VAE
  dims: [3, 32, 64, 128]
  latent: 256
  img_size: [3, 128, 128]
  down:
    conv1:
      kernel: 3
      stride: 1
      padding: 1
    conv2:
      kernel: 3
      stride: 2
      padding: 1
  up:
    conv2:
      kernel: 3
      stride: 1
      padding: 1

loss_fn: 
  name: ELBO
 
hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 200
  batch_size: 128

save_path: saved