expr: Experiment

device: cuda

data:
  dataset: CelebA
  mode: train # should consider train or test!

model:
  name: VAE
  dims: [3, 32, 64, 128, 256]
  latent: 128
  img_size: [3, 128, 128]

loss_fn: 
  name: ELBO
 
hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 200
  batch_size: 64

save_path: saved