expr: Experiment

device: cuda

data:
  dataset: MNIST
  mode: train # should consider train or test!

model:
  name: VAE
  dims: [784, 500, 200]
  latent: 10

loss_fn: 
  name: ELBO
 
hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 200
  batch_size: 128

save_path: saved