expr: Experiment

device: cuda

data:
  dataset: MNIST
  mode: train # should consider train or test!

model:
  name: VAE
  dims: [1, 32, 64]
  latent: 16
  img_size: [1, 28, 28]

loss_fn: 
  name: ELBO
 
hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 100
  batch_size: 128

save_path: saved